CREATE TABLE customers (
  id VARCHAR(36) PRIMARY KEY,
  active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  deactivated_at TIMESTAMPTZ,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  x_coordinates NUMERIC NOT NULL,
  y_coordinates NUMERIC NOT NULL
);